"""Demo-support endpoints: sample synthetic ID documents for the scoring dialog.

The ID images in data/id_documents/ were generated by ml/generate_id_documents.py;
the name printed on each card is a pure function of the application_id
(`id_document_plan` in ml/generate_synthetic_data.py), so this router can
answer "which name is on this card, and does it match the applicant?" without
any OCR — the generator's functions ARE the source of truth.
"""

from __future__ import annotations

import random
import re
import threading
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse

from app.ml.scoring_service import ML_DIR  # ensures /ml is on sys.path
from app.models import Investigator
from app.services.auth import get_current_investigator

from generate_synthetic_data import applicant_name_for, id_document_plan  # noqa: E402

router = APIRouter(prefix="/demo", tags=["demo"])

DATA_DIR = ML_DIR.parent / "data" if (ML_DIR.parent / "data" / "applications_train.csv").exists() else Path("/data")
ID_DOCS_DIR = DATA_DIR / "id_documents"
_FILENAME_RE = re.compile(r"^id_[0-9a-f]{12}\.png$")  # blocks path traversal

_samples: dict[str, list[dict]] | None = None
_lock = threading.Lock()


def _load_samples() -> dict[str, list[dict]]:
    """Index every application that has an ID document, split by match/mismatch."""
    global _samples
    if _samples is None:
        with _lock:
            if _samples is None:
                import pandas as pd

                df = pd.read_csv(DATA_DIR / "applications_train.csv")
                with_id = df[df["id_document_filename"].fillna("").str.len() > 0]
                matched: list[dict] = []
                mismatched: list[dict] = []
                for row in with_id.itertuples(index=False):
                    first, last = applicant_name_for(row.application_id)
                    id_first, id_last, is_mismatch = id_document_plan(
                        row.application_id, row.fraud_type
                    )
                    entry = {
                        "filename": row.id_document_filename,
                        "applicant_name": f"{first} {last}",
                        "id_name": f"{id_first} {id_last}",
                        "mismatch": bool(is_mismatch),
                    }
                    (mismatched if is_mismatch else matched).append(entry)
                _samples = {"matched": matched, "mismatched": mismatched}
    return _samples


@router.get("/sample-id")
def sample_id(
    mismatch: bool = Query(default=False),
    _: Investigator = Depends(get_current_investigator),
) -> dict:
    """A random sample ID card, either matching the applicant or deliberately not."""
    samples = _load_samples()
    pool = samples["mismatched" if mismatch else "matched"]
    if not pool:
        raise HTTPException(status_code=404, detail="No sample ID documents available")
    entry = random.choice(pool)
    return {**entry, "image_url": f"/demo/id-image/{entry['filename']}"}


@router.get("/id-image/{filename}")
def id_image(
    filename: str,
    _: Investigator = Depends(get_current_investigator),
) -> FileResponse:
    if not _FILENAME_RE.match(filename):
        raise HTTPException(status_code=404, detail="Unknown document")
    path = ID_DOCS_DIR / filename
    if not path.exists():
        raise HTTPException(status_code=404, detail="Document image not found")
    return FileResponse(path, media_type="image/png")
